# Numpy

NumPy is a Python package. It stands for 'Numerical Python'. It is a library consisting of multidimensional array objects and a collection of routines for processing of array.


In [30]:
import numpy as np

In [2]:
x = np.array([1,2,3,4],ndmin = 3)
x

array([[[1, 2, 3, 4]]])

In [3]:
x1 = np.array([1,2,3],dtype = complex)
x1

array([1.+0.j, 2.+0.j, 3.+0.j])

In [44]:
dt = np.dtype([('age',np.int8)])
a = np.array([(10,),(20,),(30,)],dtype = dt)
a

array([(10,), (20,), (30,)], dtype=[('age', 'i1')])

In [45]:
print(a['age'])

[10 20 30]


In [28]:
a = np.array([[2,3,4],
              [4,5,7]])
print(a)
print(a.shape)

[[2 3 4]
 [4 5 7]]
(2, 3)


In [29]:
x = np.linspace(1,4,5)
x

array([1.  , 1.75, 2.5 , 3.25, 4.  ])

In [30]:
x1 = np.tile(np.linspace(1,3,5),3)
x1

array([1. , 1.5, 2. , 2.5, 3. , 1. , 1.5, 2. , 2.5, 3. , 1. , 1.5, 2. ,
       2.5, 3. ])

In [71]:
l1 = np.logspace(5,10,num = 10)
l1

array([1.00000000e+05, 3.59381366e+05, 1.29154967e+06, 4.64158883e+06,
       1.66810054e+07, 5.99484250e+07, 2.15443469e+08, 7.74263683e+08,
       2.78255940e+09, 1.00000000e+10])

In [73]:
l2 = np.logspace(1,10,num =10,base = 2 )
l2

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

In [31]:
y = np.array([2,4])
y

array([2, 4])

In [32]:
y1 = np.repeat(np.array([2,4]),3)
y1

array([2, 2, 2, 4, 4, 4])

In [48]:
a = np.arange(1,21)
a
print(a.ndim)

1


In [75]:
a = np.arange(10)
a[2:7]

array([2, 3, 4, 5, 6])

In [76]:
a = np.array([[1,2,3],[3,4,5],[5,6,7]])
a

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [83]:
#slicing array 
print(a[...,1])
print('\n')
print(a[0],'\n')
print(a[0][0],'\n')
print(a[1],'\n')
print(a[2])

[2 4 6]


[1 2 3] 

1 

[3 4 5] 

[5 6 7]


In [85]:
print(a,'\n')
print(a[...,2],'\n')
print(a[2,...])

[[1 2 3]
 [3 4 5]
 [5 6 7]] 

[3 5 7] 

[5 6 7]


In [88]:
print(a,"\n")
print(a[1:],"\n")
print(a[...,1:])

[[1 2 3]
 [3 4 5]
 [5 6 7]] 

[[3 4 5]
 [5 6 7]] 

[[2 3]
 [4 5]
 [6 7]]


In [52]:
b = a.reshape(2,5,2)
b

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [53]:
m =np.array([1,2,3,4],dtype = np.int8)
print(m.itemsize)

1


In [55]:
m1 = np.array([1,2,3,4,5,6],dtype = np.float32)
print(m1.itemsize)

4


In [56]:
m2 = np.empty([3,2],dtype = int)
m2

array([[1065353216, 1073741824],
       [1077936128, 1082130432],
       [1084227584, 1086324736]])

In [58]:
m3 = np.zeros((3,3),dtype = int)
m3

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [59]:
m4 = np.ones((4,4),dtype = int)
m4

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [61]:
z = [2,3,4]
z1 = np.asarray(z,dtype = int)
z1

array([2, 3, 4])

In [62]:
z = (3,4,5)
z2 = np.asarray(z)
z2

array([3, 4, 5])

In [63]:
n = [(1,2,4),(3,5),8]
n1 = np.asarray(n)
n1

array([(1, 2, 4), (3, 5), 8], dtype=object)

In [92]:
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 
print(x,'\n')
print(x[0:3])
print(x[...,1])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[ 1  4  7 10]


In [94]:
rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]]) 
print(rows)
print(cols)

[[0 0]
 [3 3]]
[[0 2]
 [0 2]]


In [95]:
print(x[rows,cols])

[[ 0  2]
 [ 9 11]]


In [100]:
print(x,"\n")
print(x[1:3,0:3])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 

[[3 4 5]
 [6 7 8]]


In [34]:
a1 = np.random.randint(1,10,(3,3))
a1

array([[2, 1, 6],
       [9, 8, 5],
       [4, 9, 1]])

In [35]:
a2 = np.random.randint(1,30,(3,4))
a2

array([[22, 19,  8,  2],
       [18,  9,  5, 27],
       [ 8, 19, 17, 26]])

In [36]:
a1.shape,a2.shape

((3, 3), (3, 4))

In [37]:
a1.T

array([[2, 9, 4],
       [1, 8, 9],
       [6, 5, 1]])

In [38]:
a2.T

array([[22, 18,  8],
       [19,  9, 19],
       [ 8,  5, 17],
       [ 2, 27, 26]])

In [39]:
a3 = np.dot(a1.T,a2)
a3

array([[238, 195, 129, 351],
       [238, 262, 201, 452],
       [230, 178,  90, 173]])

In [19]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [22]:
z = np.arange(1,50).reshape(7,7)
z

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [24]:
z[4,6]

35

In [26]:
z[2:5,5:7]

array([[20, 21],
       [27, 28],
       [34, 35]])

In [6]:
a = np.arange(0,60,5)


print(a.reshape(3,4),"\n")

for x in np.nditer(a):
    print(x)


[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]] 

0
5
10
15
20
25
30
35
40
45
50
55


In [7]:
b = a.T
b

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [17]:
a = np.arange(0,60,5)
a = a.reshape(3,4)
print(a,"\n")

b = a.T
print(b,'\n')

print("sorted in C style")
c = b.copy(order = "C")
print(c)
for x in np.nditer(c):
    print(x)

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]] 

[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]] 

sorted in C style
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0
20
40
5
25
45
10
30
50
15
35
55


In [19]:
c2 = b.copy(order = "F")
print("sorted in F style")
print(c2,"\n")
for x in np.nditer(c2):
    print(x)

sorted in F style
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]] 

0
5
10
15
20
25
30
35
40
45
50
55


In [23]:
print("original array","\n",a)

for x in np.nditer(a,op_flags = ["readwrite"]):
    x[...] = 2*x
    
print("modified array","\n",a)

original array 
 [[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
modified array 
 [[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]


In [3]:
x = np.random.randint(10,size = (2,3))
x

array([[8, 2, 0],
       [8, 7, 1]])

In [4]:
x1 = np.random.randint(10,size = (2,3,3))
x1

array([[[9, 8, 7],
        [4, 0, 9],
        [4, 2, 2]],

       [[7, 8, 0],
        [9, 5, 4],
        [1, 0, 9]]])

In [6]:
x1[:2,:2,:1]

array([[[9],
        [4]],

       [[7],
        [9]]])

In [13]:
x1[1][2]

array([1, 0, 9])

In [29]:
x1[0][1:,:2],x1[0][1:]

(array([[4, 0],
        [4, 2]]),
 array([[4, 0, 9],
        [4, 2, 2]]))

In [30]:
x2 = np.random.randint(10,size = (2,3,3,4))
x2

array([[[[9, 6, 6, 1],
         [5, 2, 0, 6],
         [3, 9, 6, 7]],

        [[0, 2, 0, 7],
         [4, 0, 8, 7],
         [6, 5, 0, 4]],

        [[2, 1, 9, 9],
         [4, 3, 6, 5],
         [7, 9, 0, 9]]],


       [[[9, 9, 1, 7],
         [2, 9, 7, 0],
         [7, 9, 2, 3]],

        [[5, 9, 2, 9],
         [8, 5, 9, 1],
         [0, 2, 8, 7]],

        [[4, 9, 6, 8],
         [7, 1, 9, 7],
         [9, 3, 8, 4]]]])

In [46]:
x2[1][1][1:3,1:3],x2[1][2][2:,2:]

(array([[5, 9],
        [2, 8]]),
 array([[8, 4]]))

In [4]:
mat1 = np.random.randint(10,size = (5,3))
mat1

array([[6, 6, 2],
       [2, 9, 7],
       [8, 6, 4],
       [6, 5, 6],
       [5, 7, 5]])

In [5]:
mat2 = np.random.randint(10,size =(3,5))
mat2

array([[0, 2, 6, 9, 4],
       [6, 3, 0, 1, 3],
       [0, 3, 4, 7, 7]])

In [6]:
mat3 = mat1*mat2
mat3

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

In [7]:
mat2 = mat2.T
mat2

array([[0, 6, 0],
       [2, 3, 3],
       [6, 0, 4],
       [9, 1, 7],
       [4, 3, 7]])

In [8]:
mat3 = mat1*mat2
mat3

array([[ 0, 36,  0],
       [ 4, 27, 21],
       [48,  0, 16],
       [54,  5, 42],
       [20, 21, 35]])

In [10]:
a1 = np.random.randint(15,size = (2,3))
a1

array([[4, 7, 5],
       [3, 6, 2]])

In [11]:
a2 = np.random.randint(10,size = (2,3,3))
a2

array([[[4, 7, 2],
        [3, 2, 3],
        [2, 7, 0]],

       [[0, 0, 2],
        [8, 4, 2],
        [8, 6, 6]]])

In [12]:
a3 = a1*a2
a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [18]:
a1= a1.reshape(2,3,1)


In [19]:
a3 = a1*a2
a3

array([[[16, 28,  8],
        [21, 14, 21],
        [10, 35,  0]],

       [[ 0,  0,  6],
        [48, 24, 12],
        [16, 12, 12]]])

In [20]:
a1.shape,a2.shape

((2, 3, 1), (2, 3, 3))

In [23]:
a2.T
a2.shape

(2, 3, 3)

In [24]:
a4 = np.dot(a1,a2)
a4

ValueError: shapes (2,3,1) and (2,3,3) not aligned: 1 (dim 2) != 3 (dim 1)

In [4]:
m1 = np.random.randint(20,size = (3,4))
m1

array([[17,  9,  1, 18],
       [ 8, 12, 16,  9],
       [ 7,  2, 17,  6]])

In [14]:
print(m1.flat[5],"\n")
print(m1.flatten(),"\n")
print(m1.ravel())

12 

[17  9  1 18  8 12 16  9  7  2 17  6] 

[17  9  1 18  8 12 16  9  7  2 17  6]


In [21]:
s = np.arange(9).reshape(1,3,3)
s

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

In [22]:
s1 = np.squeeze(s)
print(s1,"\n")
print(s.shape,"\n")
print(s1.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

(1, 3, 3) 

(3, 3)


In [44]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print("concatenate",np.concatenate((a,b)),"\n")
print("concatenate ",np.concatenate((a,b),axis = 1))
print("")
print("stack")
print(np.stack((a,b),0),"\n")
print(np.stack((a,b),1))

concatenate [[1 2]
 [3 4]
 [5 6]
 [7 8]] 

concatenate  [[1 2 5 6]
 [3 4 7 8]]

stack
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [28]:
print("hstack \n")
print(np.hstack((a,b)))

hstack 

[[1 2 5 6]
 [3 4 7 8]]


In [29]:
print("vstack \n",np.vstack((a,b)))

vstack 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [37]:
n = np.arange(16).reshape(4,4)
print(n,"\n")

print(np.vsplit(n,2),"\n")
print("hsplit",np.hsplit(n,2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])] 

hsplit [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
