# Choosing the right Estimator/Algorithm for our problem

 * Classification - predicting whether a sample is one thing or another
 * Regression - predicting number
 * clustering - 

In [56]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Import Boston Housing data 

In [57]:
from sklearn.datasets import load_boston
boston = load_boston()
boston

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [58]:
#convert it to pandas datafrmae

boston_df = pd.DataFrame(boston["data"],columns = boston["feature_names"])
boston_df["target"] = pd.Series(boston["target"])
boston_df.head(4)

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4

In [59]:
len(boston_df)

506

In [60]:
boston_df.shape

(506, 14)

* With this dataset we are trying to predict target values.so we can say that its a regression problem.But there are many regression algorithm.which one we should try?

* For this kind of problem scikit learn provides

In [61]:
#lets try Ridge Regression

from sklearn.linear_model import Ridge
from sklearn.model_selection import train_test_split

X = boston_df.drop(["target"],axis = 1)
y = boston_df["target"]


X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3)

np.random.seed(2)

#Ridge model 
ridge = Ridge()
ridge.fit(X_train,y_train)
ridge.score(X_test,y_test)

0.6915135974043551

## How do we improve the score?
## What if Ridge regression wasn't working? Scikit learn also provides solution for this kind of problem.

Let's check the scikit learn map..https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html

In [62]:
#Let's try another regression model.Lets try Random Forest regressor

from sklearn.ensemble import RandomForestRegressor

#set random seed
np.random.seed(2)

#create the data
X = boston_df.drop(["target"],axis = 1)
y = boston_df["target"]

#split the data
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3)

#random forest model
rf = RandomForestRegressor()
rf.fit(X_train,y_train)

#evaluate the model
rf.score(X_test,y_test)


0.8950866297555207

In [63]:
print("ridge model score",ridge.score(X_test,y_test))

ridge model score 0.7600714854758328


* From above evaluation we can see that Random Forest Regressor is performing better than Ridge Regression model 

# Choosing an estimator for a classification problem

lets check the map...https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html

In [64]:
df = pd.read_csv("heart-disease.csv")
df.head(5)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [65]:
df["target"].value_counts()

1    165
0    138
Name: target, dtype: int64

In [66]:
len(df)

303

In [67]:
#create the data

X = df.drop(["target"],axis = 1)
y = df["target"]

#split the data 
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3,random_state = 3)

* our sample length is more than 50 and its predicting a category.scikit learn map guiding us based on this information that we should try LinearSVC


In [68]:
# import the linearSVC class
from sklearn.svm import LinearSVC

#instantiate the model

clf = LinearSVC()
clf.fit(X_train,y_train)

#evaluate the model
clf.score(X_test,y_test)

C:\Users\ROBIN\.conda\envs\tf-gpu\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


0.7802197802197802

In [69]:
#Lets try another classificaltion model

from sklearn.ensemble import RandomForestClassifier

clf_1 = RandomForestClassifier()
clf_1.fit(X_train,y_train)

#evaluate the model
clf_1.score(X_test,y_test)

0.8241758241758241

# Make prediction with machine learning model

In [70]:
clf.predict(X_test)

array([0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0], dtype=int64)

In [71]:
np.array(y_test)

array([0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0], dtype=int64)

In [72]:
#evaluating the model compare to truth label

y_pred = clf.predict(X_test)
np.mean(y_pred == y_test)

0.7802197802197802

In [73]:
#another way to evaluate the model

clf.score(X_test,y_test)

0.7802197802197802

In [74]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test,y_pred)

0.7802197802197802

* * Making prediction with predict_proba

* prediction_proba() return probabilities of a classification label

In [75]:
clf_1.predict_proba(X_test[:10])

array([[0.54, 0.46],
       [0.04, 0.96],
       [0.22, 0.78],
       [0.21, 0.79],
       [0.25, 0.75],
       [0.33, 0.67],
       [0.95, 0.05],
       [0.95, 0.05],
       [0.45, 0.55],
       [0.09, 0.91]])

In [76]:
#Lets predict on the same data
clf_1.predict(X_test[:10])

array([0, 1, 1, 1, 1, 1, 0, 0, 1, 1], dtype=int64)

In [77]:
df["target"].value_counts()

1    165
0    138
Name: target, dtype: int64

* making prediction on regression model


In [78]:
from sklearn.ensemble import RandomForestRegressor

X = boston_df.drop(["target"],axis = 1)
y = boston_df["target"]

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.30,random_state = 2)

model = RandomForestRegressor().fit(X_train,y_train)

y_preds = model.predict(X_test)

In [80]:
y_preds[:10]

array([22.107, 20.934, 31.941, 29.203,  8.738, 13.797, 27.382, 29.414,
       29.146, 20.318])

In [82]:
np.array(y_test[:10])

array([20.2, 15.3, 37.3, 32.5,  8.8, 14.4, 22. , 26.6, 15. , 21.5])

In [83]:
#compare predictions to the ground truth

from sklearn.metrics import mean_absolute_error

mse = mean_absolute_error(y_test,y_preds)
mse

2.1935131578947353